language: python
python:
  - 3.7

before_install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH
  - conda update --yes -q conda -c conda-forge
  - conda config --set always_yes true
  - conda config --set anaconda_upload no

install:
  - conda install -q conda-build

script:
  - conda build -c ilastik-forge -c conda-forge -c defaults conda-recipe
