channels:
  - conda-forge
dependencies:
  - h5py
  - networkx
  - numpy 2
  - pandas
  - pip
  - pytest
  - pytest-qt
  - pyqt 5.15
  - qtpy
  - python 3.11
  - setuptools_scm
  # for building the docs
  - sphinx
  - sphinx_rtd_theme
