channels:
  - conda-forge
dependencies:
  - h5py
  - networkx
  - numpy>=1.12,<2
  - pandas
  - pip
  - pytest
  - pytest-qt
  - pyqt 5.15
  - python>=3.7
  - setuptools_scm
  - vigra=1.11.1=*_1038
  # for building the docs
  - sphinx
  - sphinx_rtd_theme
