{% set setup_py_data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
    name: ilastikrag
    version: {{ setup_py_data.version }}

source:
  path: ../

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ setup_py_data.version }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    # vigra/numpy incompatibility - related to indexing with a non-tuple sequence
    # for multidimensional indexing;
    - numpy >=1.12,<1.23
    - h5py
    - pandas >=1.0
    - vigra >=1.11
    - networkx >=1.11

test:
  requires:
    - pytest
    - pytest-qt
    - pyqt >5.6
  commands:
    - pytest .

  source_files:
    - ilastikrag/tests

  imports:
    - ilastikrag

about:
  home: https://github.com/stuarteberg/ilastikrag
  license: Simplified BSD
  license_file: LICENSE-BSD
  summary: ND Region Adjacency Graph with edge feature algorithms
