name: deploy

on:
  push:
    tags:
      - '0.*'

jobs:
  package:
    runs-on: ubuntu-latest
    env:
      ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: install xvfb/deps
        run: |
          sudo apt-get update
          sudo apt-get install -yy mesa-utils libgl1-mesa-dev xvfb curl
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: bld-env
          environment-file: .github/workflows/etc/bld-environment.yml
          condarc-file: .github/workflows/etc/conda-rc-deploy.yml
          miniforge-version: latest
          conda-solver: libmamba
          conda-remove-defaults: "true"
      - name: linux conda build
        shell: bash -l {0}
        run: xvfb-run --server-args="-screen 0 1024x768x24" conda build -c conda-forge conda-recipe
