name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-w-conda-recipe:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install xvfb/deps
        run: |
          sudo apt-get update
          sudo apt-get install -yy mesa-utils libgl1-mesa-dev xvfb curl
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: bld-env
          environment-file: .github/workflows/etc/bld-environment.yml
          miniforge-variant: Miniforge3
          use-mamba: true
      - name: linux conda build test
        shell: bash -l {0}
        run: |
          xvfb-run --server-args="-screen 0 1024x768x24" conda mambabuild --override-channels \
          -c conda-forge conda-recipe
